// Generates the 4 category pages (azulejos.html, cocinas.html, banos.html,
// ventanas.html) — all on the dark editorial template, DARK_PAGES below —
// from shared header/menu markup lifted straight out of index.html (the
// single source of truth for those blocks, delimited by the
// SHARED-HEADER/SHARED-MENU comment markers) plus the 3 legal pages.
//
// Run with `npm run generate:pages` after editing this file, or after
// changing the header/menu in index.html so the new pages pick it up.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

const indexHtml = await readFile("index.html", "utf8");

function extractBetween(html, startMarker, endMarker) {
  const start = html.indexOf(startMarker);
  const end = html.indexOf(endMarker);
  if (start === -1 || end === -1) throw new Error(`Markers not found: ${startMarker}`);
  return html.slice(start + startMarker.length, end).trim();
}

const HEADER_HTML = extractBetween(
  indexHtml,
  "<!-- SHARED-HEADER:START (kept in sync across pages by scripts/generate-pages.mjs) -->",
  "<!-- SHARED-HEADER:END -->",
);
const MENU_HTML = extractBetween(
  indexHtml,
  "<!-- SHARED-MENU:START (kept in sync across pages by scripts/generate-pages.mjs) -->",
  "<!-- SHARED-MENU:END -->",
);
const FOOTER_HTML = extractBetween(
  indexHtml,
  "<!-- SHARED-FOOTER:START (kept in sync across pages by scripts/generate-pages.mjs) -->",
  "<!-- SHARED-FOOTER:END -->",
);
const WHATSAPP_HTML = extractBetween(
  indexHtml,
  "<!-- SHARED-WHATSAPP:START (kept in sync across pages by scripts/generate-pages.mjs) -->",
  "<!-- SHARED-WHATSAPP:END -->",
);

const MAPS_URL = "https://share.google/IEvxZxiaf1PpbI7Nq";
const WHATSAPP_URL = "https://wa.me/34689248559?text=Hola%2C%20quiero%20informaci%C3%B3n%20sobre%20un%20proyecto";
const ADDRESS_LINE = "Gran Via del Castell de Bairen, 20 · Gandia";
const HOURS_LINE = "Lunes a viernes, 7:00 a 19:00";
const PHONE_DISPLAY = "689 248 559";
const PHONE_TEL = "+34689248559";

const AI_IMAGE_NOTE = "<!-- TODO: imagen generada por IA, sustituir por una fotografía real de un proyecto de Xaixo Home -->";
const CONTACT_EMAIL = "javierxaixo@gmail.com";

// Open Graph / Twitter card + canonical + favicons, shared by every page.
// og:image is a 1200x630 crop generated by scripts/generate-assets.mjs from
// each page's own hero photo (assets/<hero>-og.jpg); pages with no hero of
// their own (the 3 legal pages) fall back to the home's.
const SITE_URL = "https://www.xaixohome.com";
const SITE_NAME = "Xaixo Home";
const OG_LOCALE = "es_ES";
// @id de la entidad HomeAndConstructionBusiness definida en index.html —
// las páginas de categoría y legales la referencian por @id en vez de
// repetir su definición completa.
const BUSINESS_ID = `${SITE_URL}/#negocio`;
function metaMarkup({ title, description, path, ogImage }) {
  const url = `${SITE_URL}${path}`;
  const imageUrl = `${SITE_URL}/og/${ogImage}.jpg`;
  return `<link rel="canonical" href="${url}">
<link rel="icon" href="/favicon.ico" sizes="32x32">
<link rel="icon" type="image/png" href="assets/icon-512.png" sizes="512x512">
<link rel="apple-touch-icon" href="assets/apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="${SITE_NAME}">
<meta property="og:locale" content="${OG_LOCALE}">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${imageUrl}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${title}">
<meta name="twitter:description" content="${description}">
<meta name="twitter:image" content="${imageUrl}">`;
}

// JSON-LD de una página de categoría: WebPage (isPartOf/about apuntan a la
// entidad del negocio por @id), BreadcrumbList (Inicio > categoría) y la
// oferta de esa categoría (venta de material vs venta con instalación
// propia), colgada de un nodo con el mismo @id del negocio.
function offerItemOfferedMarkup(offer) {
  const base = { "@type": offer.type, name: offer.name };
  if (offer.brand) base.brand = { "@type": "Brand", name: offer.brand };
  if (offer.type === "Service") base.provider = { "@id": BUSINESS_ID };
  else base.category = "Material de construcción";
  return base;
}

function structuredDataMarkup(page) {
  const url = `${SITE_URL}/${page.slug}`;
  const graph = [
    {
      "@type": "WebPage",
      "@id": `${url}#webpage`,
      url,
      name: page.title,
      description: page.description,
      inLanguage: "es",
      isPartOf: { "@id": BUSINESS_ID },
      about: { "@id": BUSINESS_ID },
    },
    {
      "@type": "BreadcrumbList",
      "@id": `${url}#breadcrumb`,
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Inicio", item: `${SITE_URL}/` },
        { "@type": "ListItem", position: 2, name: page.hero.title, item: url },
      ],
    },
    {
      "@type": "HomeAndConstructionBusiness",
      "@id": BUSINESS_ID,
      makesOffer: {
        "@type": "Offer",
        url,
        itemOffered: offerItemOfferedMarkup(page.offer),
        description: page.offer.description,
      },
    },
  ];
  return `<script type="application/ld+json">
${JSON.stringify({ "@context": "https://schema.org", "@graph": graph }, null, 2)}
</script>`;
}

// JSON-LD de las páginas legales: solo BreadcrumbList (Inicio > página).
function legalBreadcrumbMarkup(page) {
  const url = `${SITE_URL}/${page.slug}`;
  const name = page.title.split(" | ")[0];
  const json = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "@id": `${url}#breadcrumb`,
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Inicio", item: `${SITE_URL}/` },
      { "@type": "ListItem", position: 2, name, item: url },
    ],
  };
  return `<script type="application/ld+json">
${JSON.stringify(json, null, 2)}
</script>`;
}

// Brand tags (ticker + per-product pills): looks for assets/logos/<slug>-mono.png
// — the flat white-on-transparent cutout scripts/generate-assets.mjs derives
// from whatever raw logo the user drops into assets/logos/ — and falls back
// to the brand name as plain text when it isn't there yet. Run
// `npm run generate:assets` after adding a raw logo, then `npm run generate:pages`
// so this check (done at generation time, not in the browser) picks it up.
function slugifyBrand(name) {
  return name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
// A brand is either a plain name, or { name, scale } when its logo reads
// smaller than its neighbors at the shared height (e.g. a squarer mark) and
// needs a manual bump — dark.css turns --logo-scale into a CSS transform.
function brandMarkup(brand) {
  const { name, scale } = typeof brand === "string" ? { name: brand, scale: undefined } : brand;
  const logo = `assets/logos/${slugifyBrand(name)}-mono.png`;
  if (!existsSync(logo)) return `<span>${name}</span>`;
  const style = scale ? ` style="--logo-scale: ${scale}"` : "";
  const dataScale = scale ? ` data-scale="${scale}"` : "";
  return `<span class="dk-brand-logo"${dataScale}${style}><img src="${logo}" alt="${name}" loading="lazy"></span>`;
}

// width/height per source photo, from assets/*.webp real dimensions
const IMAGE_DIMS = {
  kitchen: [1600, 1067],
  bathroom: [1067, 1600],
  living: [1600, 1067],
  exterior: [1600, 1067],
  house: [1600, 936],
  "banos-hero": [1376, 768],
  "banos-platos": [1200, 896],
  "banos-muebles": [1200, 896],
  "banos-griferia": [896, 1200],
  "banos-ceramica": [1200, 896],
  "banos-showroom": [1920, 1080],
  "azulejos-hero": [2400, 1350],
  "azulejos-suelos": [1200, 896],
  "azulejos-revestimientos": [896, 1200],
  "azulejos-exterior": [2336, 1744],
  "azulejos-formatos": [1744, 2336],
  "cocinas-hero": [2688, 1520],
  "cocinas-mobiliario": [1168, 880],
  "cocinas-encimeras": [1168, 880],
  "cocinas-electrodomesticos": [1168, 880],
  "cocinas-montaje": [880, 1168],
  "ventanas-hero": [1344, 752],
  "ventanas-pvc": [1344, 752],
  "ventanas-aluminio": [1168, 880],
  "ventanas-correderas": [880, 1168],
  "ventanas-instalacion": [880, 1168],
};

// --- Dark editorial template, shared by all 4 category pages. CSS lives in
// dark.css, loaded alongside styles.css for the shared header/menu/footer/
// WhatsApp button, @font-face and reveal-on-scroll system.
const DARK_PAGES = [
  {
    slug: "azulejos",
    title: "Azulejos y porcelánico en Gandia | Xaixo Home",
    description:
      "Suelos porcelánicos, revestimientos, exterior y grandes formatos en el showroom de Xaixo Home en Gandia. También con zona de stock para llevar al momento.",
    themeColor: "#1c1815",
    offer: {
      type: "Product",
      name: "Azulejos y porcelánico",
      description: "Venta de material de azulejos y porcelánico; no incluye instalación.",
    },
    extra: {
      id: "guia",
      heading: "Cómo elegir tu azulejo",
      paragraphs: [
        "El porcelánico y la cerámica no son el mismo material, aunque a veces se confundan. El porcelánico se cuece a temperaturas más altas y apenas absorbe agua, así que aguanta mejor el paso, la humedad y el frío: es lo que recomendamos para suelo, exterior y zonas de mucho tránsito. La cerámica de pasta blanca es más económica y sigue siendo una buena opción para revestir paredes de baño o cocina, donde no recibe pisadas.",
        "El acabado rectificado tiene los cantos cortados con precisión después de la cocción, lo que permite colocar las piezas con una junta mínima y un resultado más continuo. Si buscas un suelo con apenas líneas visibles, pide piezas rectificadas.",
        "También trabajamos grandes formatos, que reducen el número de juntas y dan sensación de continuidad, aunque necesitan una base bien nivelada y un instalador con experiencia.",
        "Para terraza, playa de piscina o cualquier exterior, el material debe ser antideslizante: buscamos piezas con clasificación de resistencia al deslizamiento C3, la adecuada para superficies mojadas, y resistentes a heladas y a la sal.",
        "Para calcular cuánto material necesitas, a los metros cuadrados reales del espacio conviene sumarles un margen de merma por roturas de corte, ajustes en esquinas y algún repuesto para el futuro: normalmente entre un 10 y un 15%, algo más si el formato es grande o hay muchos rincones. En el showroom te ayudamos a calcularlo sobre tu plano o tus medidas.",
        "Además del showroom, tenemos una amplia zona de cerámica en stock, con muchos metros cuadrados disponibles para llevar al momento y a muy buen precio. Si tu obra no puede esperar a un pedido, pregúntanos por lo que tenemos en almacén.",
        "Trabajamos con Navarti, Halcón Cerámicas, KTL, Vilar Albaro, Tercocer, Alaplana y Benesol, entre otros fabricantes. Nuestro papel es vender el material y asesorarte para elegirlo bien; la colocación la realiza el alicatador de tu obra.",
        `Si tu proyecto necesita también cemento cola, mortero u otro material de construcción, lo encontrarás en <a href="https://materialesxaixo.com" target="_blank" rel="noopener">materialesxaixo.com</a>, nuestra tienda hermana especializada en material de obra.`,
      ],
    },
    hero: {
      image: "azulejos-hero",
      alt: "Salón con suelo de porcelánico travertino y vista al mar a través de una puerta corredera, imagen de referencia",
      position: "center 58%",
      aiImage: true,
      title: "Azulejos",
      subtitle: "Suelos, revestimientos y grandes formatos de los mejores fabricantes. Los ves en el showroom de Gandia; te los servimos en obra.",
    },
    intro: {
      html: "Un azulejo se elige con luz natural. <b>Ven, compara piezas reales</b> y llévate el metro cuadrado calculado.",
      note: "No hacemos la instalación: te asesoramos, calculamos las cantidades exactas y lo servimos en obra listo para tu alicatador. Si no tienes uno, te ponemos en contacto con profesionales de confianza.",
    },
    products: [
      {
        title: "Suelos porcelánicos",
        desc: "Gran formato y formato tradicional, antideslizante para baño y cocina. Rectificado para junta mínima.",
        brands: ["Halcón Cerámicas", "KTL", "Vilar Albaro"],
        image: "azulejos-suelos",
        imageAlt: "Detalle de suelo porcelánico rectificado, vista a ras de suelo, imagen de referencia",
        aiImage: true,
      },
      {
        title: "Revestimientos",
        desc: "Pasta blanca y porcelánico para pared, en mate, brillo y relieve. Formatos desde 20 × 20 cm hasta gran formato.",
        brands: ["Alaplana", "Tercocer"],
        image: "azulejos-revestimientos",
        imageAlt: "Revestimiento cerámico acanalado en tono madera con balda y jarrón, imagen de referencia",
        imagePosition: "center 55%",
        aiImage: true,
      },
      {
        title: "Exterior y piscina",
        desc: "Antideslizante clase C3, apto para playa de piscina y terraza. Resistente a heladas y a la sal.",
        brands: ["Navarti", "Benesol"],
        image: "azulejos-exterior",
        imageAlt: "Terraza con pavimento porcelánico antideslizante junto a una piscina, imagen de referencia",
        aiImage: true,
      },
      {
        title: "Grandes formatos",
        desc: "Piezas de hasta 320 × 160 cm para suelo continuo o revestimiento sin apenas juntas. Cortadas a medida en el showroom.",
        brands: ["Tercocer", "Alaplana"],
        image: "azulejos-formatos",
        imageAlt: "Ducha revestida con una lámina de porcelánico de gran formato efecto mármol, imagen de referencia",
        aiImage: true,
      },
    ],
    brandsTicker: ["Navarti", "Halcón Cerámicas", "KTL", "Vilar Albaro", "Tercocer", "Alaplana", "Benesol"],
    steps: [
      { title: "Nos cuentas tu proyecto", desc: "Por WhatsApp o en el showroom. Con metros aproximados o un plano, mejor; sin ellos, también." },
      { title: "Elegimos juntos el material", desc: "Ves y tocas piezas reales, comparas con luz natural. Sales con un presupuesto cerrado." },
      { title: "Te lo servimos en obra", desc: "Todo en una entrega, en la fecha que necesite tu alicatador." },
    ],
    cta: {
      image: "banos-showroom",
      alt: "Fachada del showroom de Xaixo Home en Gandia",
      position: "center 62%",
      heading: "Ven a verlo<br>con tus ojos.",
      primary: { label: "Visita el showroom", href: MAPS_URL, external: true },
      secondary: { label: "Escríbenos por WhatsApp", href: WHATSAPP_URL, external: true },
    },
  },
  {
    slug: "cocinas",
    title: "Cocinas a medida en Gandia | Xaixo Home",
    description:
      "Cocinas diseñadas en 3D e instaladas por nuestro propio equipo en Gandia y la Safor. Distribuidores oficiales de Nobilia, fabricante alemán.",
    themeColor: "#1c1815",
    offer: {
      type: "Service",
      name: "Cocinas a medida con instalación propia",
      brand: "Nobilia",
      description: "Diseño, suministro e instalación propia de cocinas. Distribuidor oficial de Nobilia.",
    },
    extra: {
      id: "nobilia",
      heading: "Distribuidores oficiales de Nobilia",
      paragraphs: [
        "Somos distribuidores oficiales de Nobilia, fabricante alemán de cocinas. Eso te da acceso a todo su catálogo de acabados, herrajes y módulos, con la fabricación y los controles de calidad de una de las mayores fábricas de cocinas de Europa.",
        "El proceso es siempre el mismo: medimos tu cocina actual, la diseñamos contigo en 3D y te presentamos un presupuesto cerrado antes de empezar. Una vez lo apruebas, la instalación la realiza nuestro propio equipo, de principio a fin, sin subcontratar.",
      ],
    },
    hero: {
      image: "cocinas-hero",
      alt: "Cocina abierta con isla, mobiliario en tono arena y comedor con vistas al jardín, imagen de referencia",
      position: "center 55%",
      aiImage: true,
      title: "Cocinas",
      subtitle: "Diseñadas en 3D contigo e instaladas por nuestro equipo. Del plano a la última bisagra.",
    },
    intro: {
      html: "Una cocina no se compra por catálogo. <b>Se mide, se dibuja contigo</b> y se instala sin sorpresas.",
      note: "Diseño 3D, presupuesto cerrado e instalación con nuestro propio equipo, de principio a fin. Un único interlocutor durante toda la obra.",
    },
    products: [
      {
        title: "Mobiliario",
        desc: "Módulos a medida en melamina, laminado o lacado, con herrajes de cierre suave. Despensas y columnas hasta el techo. Cocinas Nobilia, fabricadas en Alemania.",
        brands: ["Nobilia"],
        image: "cocinas-mobiliario",
        imageAlt: "Armario despensa extraíble abierto junto a estantería de madera, imagen de referencia",
        imagePosition: "72% center",
        aiImage: true,
      },
      {
        title: "Encimeras",
        desc: "Cuarzo, compacto y piedra natural, con canto recto o biselado. Fabricadas a medida de tu plano.",
        image: "cocinas-encimeras",
        imageAlt: "Encimera de cuarzo blanco con canto a inglete y fregadero integrado, imagen de referencia",
        aiImage: true,
      },
      {
        title: "Electrodomésticos",
        desc: "Integrados o de libre instalación: horno, inducción, frigorífico y lavavajillas de las mejores marcas.",
        image: "cocinas-electrodomesticos",
        imageAlt: "Horno y microondas integrados junto a placa de inducción con campana extractora, imagen de referencia",
        aiImage: true,
      },
      {
        title: "Instalación propia",
        desc: "Montaje, conexión de agua y electrodomésticos, y ajustes finales con nuestro propio equipo, sin subcontratar.",
        image: "cocinas-montaje",
        imageAlt: "Instalador montando muebles altos de cocina con nivel y taladro, imagen de referencia",
        imagePosition: "center 35%",
        aiImage: true,
      },
    ],
    brandsTicker: ["Nobilia"],
    steps: [
      { title: "Medimos en tu casa", desc: "Visitamos tu cocina actual y tomamos medidas reales, sin compromiso." },
      { title: "La diseñamos en 3D y cerramos presupuesto", desc: "Ves el resultado antes de decidir y sales con un precio cerrado." },
      { title: "La instalamos nosotros", desc: "Un único equipo, de principio a fin, sin cambios de interlocutor." },
    ],
    simulator: {
      title: "Calcula tu presupuesto orientativo",
    },
    cta: {
      image: "banos-showroom",
      alt: "Fachada del showroom de Xaixo Home en Gandia",
      position: "center 62%",
      heading: "Hablemos de<br>tu cocina.",
      primary: { label: "Pide tu presupuesto", href: "#contacto", external: false },
      secondary: { label: "Visita el showroom", href: MAPS_URL, external: true },
    },
  },
  {
    slug: "ventanas",
    title: "Ventanas de PVC y aluminio en Gandia | Xaixo Home",
    description:
      "Ventanas de PVC y aluminio medidas e instaladas por nuestro equipo en Gandia. Te informamos también de las ayudas para su cambio.",
    themeColor: "#1c1815",
    offer: {
      type: "Service",
      name: "Ventanas de PVC y aluminio con instalación propia",
      brand: "Replus",
      description: "Medición, fabricación a medida e instalación propia de ventanas. Punto de venta oficial de Replus.",
    },
    extra: {
      id: "ayudas",
      heading: "Ayudas para cambiar tus ventanas",
      paragraphs: [
        "Como punto de venta oficial Replus, te ponemos en contacto con su oficina técnica de ayudas, que tramita la subvención por ti cuando hay convocatoria abierta. Pregúntanos por la situación actual antes de pedir presupuesto.",
      ],
    },
    hero: {
      image: "ventanas-hero",
      alt: "Salón con gran ventanal corredero de aluminio abierto al mar, imagen de referencia",
      position: "center 42%",
      aiImage: true,
      title: "Ventanas",
      subtitle: "PVC y aluminio, medidas e instaladas por nosotros. Más aislamiento, más silencio, menos factura.",
    },
    intro: {
      html: "Cambiar las ventanas <b>es la reforma que más se nota</b> y menos se ve.",
      note: "Medimos, fabricamos a medida e instalamos con nuestro propio equipo. Un único responsable de principio a fin.",
    },
    products: [
      {
        title: "Ventanas de PVC",
        desc: "Perfiles multicámara con refuerzo interior. El mejor aislamiento térmico y acústico al mejor precio.",
        brands: ["Replus"],
        image: "ventanas-pvc",
        imageAlt: "Detalle de ventana de PVC oscilobatiente abierta, con manivela y perfil multicámara, imagen de referencia",
        aiImage: true,
      },
      {
        title: "Ventanas de aluminio",
        desc: "Perfil con rotura de puente térmico, esbelto y resistente. Ideal para grandes paños y diseño minimalista.",
        brands: ["Replus"],
        image: "ventanas-aluminio",
        imageAlt: "Gran ventanal fijo de aluminio con vistas a un jardín de olivos, imagen de referencia",
        aiImage: true,
      },
      {
        title: "Correderas y cerramientos",
        desc: "Correderas elevables y cerramientos de terraza con grandes paños de vidrio. Máxima apertura, mínimo perfil visto.",
        brands: ["Replus"],
        image: "ventanas-correderas",
        imageAlt: "Cerramiento corredero de aluminio negro abierto en un dormitorio con vistas al mar y terraza con tumbona, imagen de referencia",
        aiImage: true,
      },
      {
        title: "Instalación propia",
        desc: "Retirada de la ventana antigua, sellado, ajuste y limpieza final. Todo con nuestro propio equipo instalador.",
        image: "ventanas-instalacion",
        imageAlt: "Instalador comprobando con un nivel una ventana de aluminio recién colocada en un hueco de obra, con vistas al mar",
        aiImage: true,
      },
    ],
    brandsTicker: ["Replus"],
    steps: [
      { title: "Medimos en tu casa", desc: "Comprobamos huecos y el estado del cerramiento actual, sin compromiso." },
      { title: "Elegimos sistema, vidrio y color", desc: "PVC o aluminio, vidrio de control solar o acústico, y el color que combine con tu fachada." },
      { title: "Las instalamos nosotros", desc: "Retirada de las antiguas, montaje y sellado, con nuestro propio equipo." },
    ],
    cta: {
      image: "banos-showroom",
      alt: "Fachada del showroom de Xaixo Home en Gandia",
      position: "center 62%",
      heading: "Hablemos de<br>tus ventanas.",
      primary: { label: "Pide tu presupuesto", href: "#contacto", external: false },
      secondary: { label: "Visita el showroom", href: MAPS_URL, external: true },
    },
  },
  {
    slug: "banos",
    title: "Baños a medida en Gandia | Xaixo Home",
    description:
      "Platos, mamparas, muebles, grifería y cerámica de baño en el showroom de Xaixo Home en Gandia. Te asesoramos y te lo servimos listo para tu instalador.",
    themeColor: "#1c1815",
    offer: {
      type: "Product",
      name: "Material de baño: platos de ducha, mamparas, muebles, grifería y cerámica",
      description: "Venta de material de baño; no incluye instalación.",
    },
    extra: {
      id: "guia",
      heading: "Cómo elegir plato, mampara, mueble y grifería",
      paragraphs: [
        "El plato de ducha se elige por el material y por la medida real del hueco: la resina y la carga mineral son antideslizantes de fábrica y fáciles de limpiar; la cerámica es más económica pero exige más cuidado en el mantenimiento. Los de resina y carga mineral se cortan a la medida exacta de tu hueco; los cerámicos vienen en medidas estándar.",
        "En la mampara, lo que más se nota en el día a día es el tratamiento antical del vidrio, que facilita mucho la limpieza, y si es fija o corredera: la corredera es la opción habitual cuando el hueco es estrecho, porque no necesita espacio para abrir hacia fuera.",
        "El mueble de baño puede ir suspendido o a suelo. El suspendido facilita la limpieza del suelo y queda más ligero visualmente; el mueble a suelo da algo más de capacidad de almacenaje. El lavabo puede venir integrado en el mueble o montado sobre una encimera aparte, según el acabado que busques.",
        "En grifería, la primera decisión es monomando o termostática: la termostática mantiene la temperatura del agua constante aunque cambie la presión, algo especialmente útil en la ducha. El acabado, cromo, negro mate o cepillado, es cuestión de estética y conviene que combine con el resto de la sanitaria.",
        `En el showroom te enseñamos piezas reales de cada elemento y te ayudamos a calcular lo que necesitas. Vendemos el material; la instalación la realiza el profesional de tu obra. Si además necesitas cemento cola, mortero u otro material de construcción, lo encontrarás en <a href="https://materialesxaixo.com" target="_blank" rel="noopener">materialesxaixo.com</a>, nuestra tienda hermana.`,
      ],
    },
    hero: {
      image: "banos-hero",
      alt: "Baño showroom Xaixo Home con mueble de lavabo en madera, ducha con mampara de vidrio y revestimiento de porcelánico beige",
      position: "center 30%",
      title: "Baños",
      subtitle: "Platos, mamparas, muebles, grifería y cerámica. Los eliges en el showroom de Gandia; te los servimos en obra.",
    },
    intro: {
      html: "Un baño se elige tocando. <b>Ven, compara materiales reales</b> y sal con el presupuesto cerrado.",
      note: "No hacemos la obra: te asesoramos, preparamos todo el material y lo entregamos listo para tu instalador. Si no tienes uno, te ponemos en contacto con profesionales de confianza.",
    },
    products: [
      {
        title: "Platos de ducha y mamparas",
        desc: "Resina, carga mineral y cerámica, cortados a la medida de tu hueco. Mamparas de vidrio templado con tratamiento antical, fijas o correderas.",
        image: "banos-platos",
        imageAlt: "Plato de ducha antracita con mampara de vidrio y marco negro, en ducha con revestimiento cerámico y hornacina para toallas",
      },
      {
        title: "Muebles y lavabos",
        desc: "Suspendidos, a suelo y a medida, con lavabo integrado o sobre encimera. Acabados en madera, lacado y porcelánico.",
        image: "banos-muebles",
        imageAlt: "Mueble de baño suspendido en roble con espejo redondo retroiluminado",
      },
      {
        title: "Grifería y sanitarios",
        desc: "Monomando, termostática y empotrada, en cromo, negro mate y cepillados. Inodoros suspendidos con cisterna empotrada y tapa de caída amortiguada.",
        image: "banos-griferia",
        imageAlt: "Grifería de lavabo en negro mate sobre encimera de piedra clara",
        imagePosition: "center 42%",
      },
      {
        title: "Cerámica y porcelánico",
        desc: "Grandes formatos, efecto piedra y madera, rectificados y antideslizantes para suelo de ducha. Todo en piezas reales para que lo veas con luz natural.",
        image: "banos-ceramica",
        imageAlt: "Revestimiento cerámico tipo travertino en ducha con hornacina para toallas",
      },
    ],
    steps: [
      { title: "Nos cuentas tu baño", desc: "Por WhatsApp o en el showroom. Con medidas o un plano, mejor; sin ellos, también." },
      { title: "Elegimos juntos el material", desc: "Ves y tocas piezas reales. Sales con un presupuesto cerrado, sin sorpresas." },
      { title: "Te lo servimos en obra", desc: "Todo en una entrega, en la fecha que necesite tu instalador." },
    ],
    cta: {
      image: "banos-showroom",
      alt: "Fachada del showroom de Xaixo Home en Gandia",
      position: "center 62%",
      heading: "Ven a verlo<br>con tus ojos.",
      primary: { label: "Visita el showroom", href: MAPS_URL, external: true },
      secondary: { label: "Escríbenos por WhatsApp", href: WHATSAPP_URL, external: true },
    },
  },
];

function darkImageMarkup(image, alt, { className, sizes, position, priority } = {}) {
  const [w, h] = IMAGE_DIMS[image];
  const candidateWidths = priority ? [800, 1200, 1600, 2400, w] : [800, 1200, 1600, w];
  const srcset = candidateWidths
    .filter((width, i, arr) => arr.indexOf(width) === i && width <= w)
    .map((width) => (width === w ? `assets/${image}.webp ${w}w` : `assets/${image}-${width}.webp ${width}w`))
    .join(", ");
  const style = position ? ` style="object-position: ${position};"` : "";
  const loadingAttrs = priority ? ` fetchpriority="high"` : ` loading="lazy" decoding="async"`;
  return `<img class="${className}" src="assets/${image}.webp" srcset="${srcset}" sizes="${sizes}" alt="${alt}" width="${w}" height="${h}"${loadingAttrs}${style}>`;
}

function darkHeroPreloadMarkup(image) {
  const [w] = IMAGE_DIMS[image];
  const srcset = [800, 1200, 1600, 2400, w]
    .filter((width, i, arr) => arr.indexOf(width) === i && width <= w)
    .map((width) => (width === w ? `assets/${image}.webp ${w}w` : `assets/${image}-${width}.webp ${width}w`))
    .join(", ");
  return `<link rel="preload" href="assets/${image}.webp" as="image" imagesrcset="${srcset}" imagesizes="100vw" fetchpriority="high">`;
}

function darkProductMarkup(product) {
  const image = darkImageMarkup(product.image, product.imageAlt, {
    className: "dk-pic-img",
    sizes: "(max-width: 820px) 100vw, 50vw",
    position: product.imagePosition,
  });
  const brandsHtml = product.brands?.length
    ? `\n<div class="dk-brands reveal">${product.brands.map(brandMarkup).join("")}</div>`
    : "";
  const imageNote = product.aiImage ? `${AI_IMAGE_NOTE}\n` : "";
  return `<article class="dk-prod">
<div class="dk-pic" data-cursor="VER">
${imageNote}<div class="dk-ph" data-px="0.12">${image}</div>
</div>
<div class="dk-txt">
<h2 class="reveal">${product.title}</h2>
<p class="reveal">${product.desc}</p>${brandsHtml}
</div>
</article>`;
}

function darkBrandsTickerMarkup(brands) {
  if (!brands?.length) return "";
  const spans = brands.map(brandMarkup).join("");
  return `<div class="dk-marcas" aria-label="Marcas con las que trabajamos">
<div class="dk-row">${spans}</div><div class="dk-row" aria-hidden="true">${spans}</div>
</div>`;
}

function darkStepsMarkup(steps) {
  return steps.map((step) => `<div class="dk-step reveal"><strong>${step.title}</strong><p>${step.desc}</p></div>`).join("");
}

// Bloque de texto indexable adicional (guía de compra, distribuidor
// oficial, ayudas…), específico de cada página. Reutiliza el estilo ya
// existente de .legal-page (mismo look que aviso-legal/cookies/etc.) para
// no tener que tocar el CSS.
function darkExtraMarkup(extra) {
  if (!extra) return "";
  const paragraphs = extra.paragraphs.map((p) => `<p class="reveal">${p}</p>`).join("\n");
  return `<section class="legal-page section-pad" id="${extra.id}">
<h2 class="reveal">${extra.heading}</h2>
${paragraphs}
</section>
`;
}

function darkSimulatorMarkup(simulator) {
  if (!simulator) return "";
  // TODO: simulador interactivo de presupuesto, pendiente de desarrollar.
  // Oculto (comentado) en vez de mostrar la sección con el texto de
  // "muy pronto" hasta que exista de verdad — ver el placeholder debajo.
  return `<!--
<section class="dk-sim" id="simulador">
<h3 class="reveal">${simulator.title}</h3>
<p class="reveal">Muy pronto podrás calcular aquí un presupuesto orientativo.</p>
</section>
-->
`;
}

function darkCtaButtonMarkup(button, modifierClass) {
  const targetAttrs = button.external ? ` target="_blank" rel="noopener"` : "";
  return `<a class="dk-btn ${modifierClass}" href="${button.href}"${targetAttrs}>${button.label}</a>`;
}

function darkCtaMarkup(page) {
  const { cta } = page;
  const image = darkImageMarkup(cta.image, cta.alt, {
    className: "dk-cta-img",
    sizes: "100vw",
    position: cta.position,
  });
  return `<section class="dk-cta" id="visita">
<div class="dk-ph" data-px="0.1">${image}</div>
<div class="dk-cta-in">
<div>
<h2 class="reveal">${cta.heading}</h2>
<div class="dk-btns reveal">
${darkCtaButtonMarkup(cta.primary, "dk-btn--pri")}
${darkCtaButtonMarkup(cta.secondary, "dk-btn--sec")}
</div>
</div>
<div class="dk-addr reveal">
<b>Showroom Xaixo Home</b>
${ADDRESS_LINE}<br>
${HOURS_LINE}<br>
<a href="tel:${PHONE_TEL}">${PHONE_DISPLAY}</a>
</div>
</div>
</section>`;
}

function renderDarkCategoryPage(page) {
  const heroImage = darkImageMarkup(page.hero.image, page.hero.alt, {
    className: "dk-hero-img",
    sizes: "100vw",
    position: page.hero.position,
    priority: true,
  });
  const heroImageNote = page.hero.aiImage ? `${AI_IMAGE_NOTE}\n` : "";
  const productsHtml = page.products.map(darkProductMarkup).join("\n");
  const brandsTicker = darkBrandsTickerMarkup(page.brandsTicker);
  const stepsHtml = darkStepsMarkup(page.steps);
  const simulatorSection = darkSimulatorMarkup(page.simulator);

  return `<!doctype html>
<html lang="es">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="${page.themeColor}"><title>${page.title}</title>
<meta name="description" content="${page.description}">
${metaMarkup({ title: page.title, description: page.description, path: `/${page.slug}`, ogImage: page.hero.image })}
<link rel="preload" href="assets/manrope-variable.woff2" as="font" type="font/woff2" crossorigin>
${darkHeroPreloadMarkup(page.hero.image)}
<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="dark.css">
<script type="module" src="/app.js"></script>
${structuredDataMarkup(page)}
</head>
<body class="dark-page">
<a class="skip" href="#intro">Saltar al contenido</a>
${HEADER_HTML}
<main>
<section class="dk-hero" id="inicio" aria-label="${page.hero.title}">
${heroImageNote}<div class="dk-ph" data-px="0.18">${heroImage}</div>
<div class="dk-hero-txt">
<h1>${page.hero.title}</h1>
<p class="dk-hero-sub">${page.hero.subtitle}</p>
</div>
<div class="dk-scroll-hint" aria-hidden="true"></div>
</section>
<section class="dk-intro" id="intro">
<p class="reveal">${page.intro.html}</p>
<small class="reveal">${page.intro.note}</small>
</section>
<div class="dk-products">
${productsHtml}
</div>
${brandsTicker}
${darkExtraMarkup(page.extra)}<section class="dk-proc">
<h3 class="reveal">Así lo hacemos</h3>
<div class="dk-steps">
${stepsHtml}
</div>
</section>
${simulatorSection}${darkCtaMarkup(page)}
</main>
${FOOTER_HTML}
${MENU_HTML}
<div class="context-cursor" aria-hidden="true"></div>
${WHATSAPP_HTML}
</body>
</html>
`;
}

const LEGAL_PAGES = [
  {
    slug: "aviso-legal",
    title: "Aviso Legal | Xaixo Home",
    description: "Condiciones de uso y datos identificativos del titular del sitio web de Xaixo Home.",
    heading: "AVISO LEGAL",
    bodyHtml: `<h2 class="reveal">1. Datos identificativos</h2>
<p class="reveal">En cumplimiento del deber de información recogido en el artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico, se informa de los siguientes datos: el titular de este sitio web es MATERIALES XAIXO HOME S.L. (Xaixo Home), con CIF B10533552, y domicilio en Gran Via del Castell de Bairen, 20, 46701 Gandia (Valencia). Puedes contactar en ${CONTACT_EMAIL}.</p>
<h2 class="reveal">2. Objeto</h2>
<p class="reveal">El presente sitio web tiene por objeto ofrecer información sobre los materiales y servicios de azulejos, cocinas, baños y ventanas de Xaixo Home.</p>
<h2 class="reveal">3. Condiciones de uso</h2>
<p class="reveal">El acceso a este sitio web es gratuito y su uso implica la aceptación plena de las condiciones aquí recogidas. El usuario se compromete a hacer un uso adecuado de los contenidos y a no emplearlos para incurrir en actividades ilícitas o contrarias a la buena fe.</p>
<h2 class="reveal">4. Propiedad intelectual e industrial</h2>
<p class="reveal">Los contenidos de este sitio web (textos, imágenes, diseño y código) son propiedad de Xaixo Home o de terceros que han autorizado su uso, y están protegidos por la normativa de propiedad intelectual e industrial. Queda prohibida su reproducción total o parcial sin autorización expresa.</p>
<h2 class="reveal">5. Responsabilidad</h2>
<p class="reveal">Xaixo Home no se hace responsable de los daños derivados de un uso inadecuado de este sitio web, ni garantiza la ausencia de interrupciones o errores en el acceso al mismo.</p>
<h2 class="reveal">6. Legislación aplicable</h2>
<p class="reveal">Las presentes condiciones se rigen por la legislación española. Para cualquier controversia serán competentes los juzgados y tribunales del domicilio del titular, salvo que la normativa de consumidores establezca otro fuero.</p>`,
  },
  {
    slug: "politica-privacidad",
    title: "Política de Privacidad | Xaixo Home",
    description: "Cómo trata Xaixo Home los datos personales de las personas usuarias del sitio web.",
    heading: "POLÍTICA DE PRIVACIDAD",
    bodyHtml: `<h2 class="reveal">1. Responsable del tratamiento</h2>
<p class="reveal">El responsable del tratamiento de los datos personales recabados a través de este sitio web es MATERIALES XAIXO HOME S.L. (Xaixo Home), con CIF B10533552, domicilio en Gran Via del Castell de Bairen, 20, 46701 Gandia (Valencia), teléfono 689 248 559 y correo ${CONTACT_EMAIL}.</p>
<h2 class="reveal">2. Finalidad del tratamiento</h2>
<p class="reveal">Los datos facilitados a través de los formularios de contacto o WhatsApp se utilizan para atender consultas, elaborar presupuestos y gestionar la relación comercial con la persona usuaria.</p>
<h2 class="reveal">3. Legitimación</h2>
<p class="reveal">La base legal para el tratamiento es el consentimiento de la persona interesada, prestado al facilitar sus datos y contactar con Xaixo Home.</p>
<h2 class="reveal">4. Destinatarios</h2>
<p class="reveal">Los datos no se cederán a terceros salvo obligación legal. Podrán tratarse a través de proveedores de servicios (por ejemplo, alojamiento web o mensajería) que actúan como encargados del tratamiento.</p>
<h2 class="reveal">5. Derechos de las personas interesadas</h2>
<p class="reveal">Puedes ejercer tus derechos de acceso, rectificación, supresión, oposición, limitación y portabilidad enviando un correo o escribiendo al domicilio indicado, adjuntando copia de un documento que acredite tu identidad.</p>
<h2 class="reveal">6. Conservación de los datos</h2>
<p class="reveal">Los datos se conservarán mientras sean necesarios para la finalidad para la que se recabaron y, posteriormente, durante los plazos legalmente exigibles.</p>`,
  },
  {
    slug: "cookies",
    title: "Política de Cookies | Xaixo Home",
    description: "Qué cookies utiliza el sitio web de Xaixo Home y cómo puedes gestionarlas.",
    heading: "POLÍTICA DE COOKIES",
    bodyHtml: `<h2 class="reveal">1. Qué son las cookies</h2>
<p class="reveal">Las cookies son pequeños archivos que se almacenan en tu navegador al visitar un sitio web. Se utilizan para recordar tus preferencias y mejorar el funcionamiento del sitio.</p>
<h2 class="reveal">2. Cookies utilizadas en este sitio</h2>
<p class="reveal"><b>Técnicas (necesarias).</b> Este sitio guarda en tu navegador la elección que hagas en el aviso de cookies, para no volver a preguntarte. No requieren consentimiento y no se usan con fines estadísticos ni publicitarios.</p>
<p class="reveal"><b>De analítica (solo si las aceptas).</b> Utilizamos Metricool, una herramienta de analítica web, con finalidad exclusivamente estadística: conocer cuántas personas visitan el sitio, qué páginas consultan y cómo llegan a él, para mejorar sus contenidos. Metricool solo se carga si pulsas «Aceptar» en el aviso de cookies; si pulsas «Rechazar», no se carga ni se recoge ningún dato con ella. Puedes consultar cómo trata Metricool la información en <a href="https://metricool.com" rel="noopener" target="_blank">metricool.com</a>.</p>
<h2 class="reveal">3. Cómo gestionar las cookies</h2>
<p class="reveal">Puedes cambiar tu elección sobre la analítica en cualquier momento con el botón siguiente. Al retirar el consentimiento la página se recarga y Metricool deja de ejecutarse.</p>
<p class="reveal"><button type="button" class="dk-btn dk-btn--sec" data-cookie-settings>Configurar cookies</button></p>
<p class="reveal">Además, puedes permitir, bloquear o eliminar las cookies instaladas en tu equipo mediante la configuración de tu navegador. Consulta su ayuda para más información.</p>`,
  },
];

function renderLegalPage(page) {
  return `<!doctype html>
<html lang="es">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#1c1815"><title>${page.title}</title>
<meta name="description" content="${page.description}">
${metaMarkup({ title: page.title, description: page.description, path: `/${page.slug}`, ogImage: "home-hero" })}
<link rel="preload" href="assets/manrope-variable.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="dark.css">
<script type="module" src="/app.js"></script>
${legalBreadcrumbMarkup(page)}
</head>
<body class="dark-page">
<a class="skip" href="#legal-content">Saltar al contenido</a>
${HEADER_HTML}
<main>
<section class="legal-page section-pad" id="legal-content">
<h1 class="reveal">${page.heading}</h1>
${page.bodyHtml}
</section>
</main>
${FOOTER_HTML}
${MENU_HTML}
${WHATSAPP_HTML}
</body>
</html>
`;
}

for (const page of DARK_PAGES) {
  const html = renderDarkCategoryPage(page);
  await writeFile(`${page.slug}.html`, html);
  console.log(`${page.slug}.html`);
}

for (const page of LEGAL_PAGES) {
  const html = renderLegalPage(page);
  await writeFile(`${page.slug}.html`, html);
  console.log(`${page.slug}.html`);
}

// sitemap.xml: the 8 URLs in the clean (no ".html") form the site is
// published under — lives in public/ so Vite copies it to dist/ as-is,
// same reasoning as public/favicon.ico (see generate-assets.mjs).
const sitemapUrls = ["/", ...[...DARK_PAGES, ...LEGAL_PAGES].map((page) => `/${page.slug}`)];
const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapUrls.map((path) => `<url><loc>${SITE_URL}${path}</loc></url>`).join("\n")}
</urlset>
`;
await mkdir("public", { recursive: true });
await writeFile("public/sitemap.xml", sitemapXml);
console.log("public/sitemap.xml");
